# Generated by Django 3.0.4 on 2020-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_joined_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=50, verbose_name='النوع :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined_us',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الانضمام :'),
        ),
    ]
