# Generated by Django 3.0.4 on 2020-04-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200410_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('جلدية', 'جلدية'), ('أسنان', 'أسنان'), ('نفسي', 'نفسي'), ('أطفال حديثي الولادة', 'أطفال حديثي الولادة'), ('مخ وأعصاب', 'مخ وأعصاب'), ('عظام', 'عظام'), ('نساء وتوليد', 'نساء وتوليد'), ('أنف وأذن وحنجرة', 'أنف وأذن وحنجرة'), ('قلب وأوعية دموية', 'قلب وأوعية دموية'), ('أمراض دم', 'أمراض دم'), ('أورام', 'أورام'), ('باطنة', 'باطنة'), ('تخسيس وتغذية', 'تخسيس وتغذية')], max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
    ]
